version: '3.8'
services:
  starrocks-alone:
    user: root
    image: allin1-ubuntu:latest
    container_name: starrocks-alone
    hostname: StarRocks-alone-01
    ports:
      - "9030:9030"
    volumes:
      - ./volumes/fe/init.sql:/data/init/init.sql
      - ./volumes/fe/fe-meta:/data/deploy/starrocks/fe/meta
    environment:
      - FE_TYPE=LEADER
    networks:
      - starrocks-network

networks:
  starrocks-network:
    driver: bridge
